config/routes.rb
SampleApp::Application.routes.draw do

  get "projects/new"

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  resources :projects do
    resources :issue_types
  end

  

  root :to => 'sessions#new'

  match '/signup', :to => 'users#new'
  match '/signout', :to => 'sessions#destroy', via: :delete
    

  match '/help', :to => 'static_pages#help'
  match '/about', :to => 'static_pages#about'
  match '/contact', :to => 'static_pages#contact'
 

  match 'substantive_content', :to => 'projects#substantive_content'
  match 'projects/:id/donot_know', :to => 'projects#donot_know', as: :projects_donot_know

  match 'projects/:id/issues', :to => 'projects#issues', as: :projects_issues
  match 'projects/:id/new_issue', :to=>'projects#new_issue', as: :new_project_issue
  
  

end

app/controllers/issue_types_controller.rb
class IssueTypesController < ApplicationController
  
  def index
  	@project = Project.find(params[:project_id])
    @issue_types = @project.issue_types.all
  end
  
  def new
    @project = Project.find(params[:project_id])
    @issue_type = @project.issue_types.build
    respond_to do |format|               
      format.js
    end
  end
  
  def create
  	@project = Project.find(params[:project_id])
  	@issue_type = @project.issue_types.build(params[:issue_type])
	  if @issue_type.save
	    flash[:success] = "Issue type created!"
      redirect_to :back
	  else
	    flash[:error] = "Issue type is not created!"
      redirect_to :back
	  end
  end

  def edit
    @project = Project.find(params[:project_id])
    @issue_type = @project.issue_types.find(params[:id])
    respond_to do |format|               
      format.js
    end
  end

  def update
    @project = Project.find(params[:project_id])
    @issue_type = @project.issue_types.find(params[:id])
    if @issue_type.update_attributes(params[:issue_type])
      flash[:success] = "Issue type updated!"
      redirect_to :back
    else
      flash[:error] = "Issue type is not updated!"
      #redirect_to :back
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @issue_type = @project.issue_types.find(params[:id])
    @issue_type.destroy
    redirect_to project_issue_types_path(@project)
  end
end

app/helpers/issue_types_helper.rb
module IssueTypesHelper
end

app/views/issue_types/_edit_issue_type_modal.html.erb
<%= form_for([@project, @issue_type]) do |f| %>
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h3>Modal header</h3>
</div>
<div class="modal-body">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div class="modal-footer">
  <a href="#" class="btn">Close</a>
  <%= f.submit "Update Issue Type", class: "btn btn-primary" %> 
  </div>
<% end %>  

app/views/issue_types/_issue_type.html.erb
  <a href='#'><%= issue_type.name %></a>

app/views/issue_types/_new_issue_type_modal.html.erb
<%= form_for([@project, @issue_type]) do |f| %>
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h3>Modal header</h3>
</div>
<div class="modal-body">
  Name
  <%= f.text_field :name %>
  <!--more form fields-->    
</div>
<div class="modal-footer">
  <a href="#" class="btn">Close</a>
  <%= f.submit "Add Issue Type", class: "btn btn-primary" %> 
  </div>
<% end %>  

app/views/issue_types/edit.js.erb
$("#edit_issue_type_modal").html("<%= escape_javascript(render 'edit_issue_type_modal') %>");

app/views/issue_types/index.html.erb

<%= render 'shared/project_info' %>
<div class="row">
  <div class="span2">
    <%= render 'shared/project_left_menu' %>
  </div>
  <div id="content" class="span8">
  	<table class="table table-striped">
  	  <thead>
  		<tr>
  	  	  <th>Issue Type</th>
  	  	  <th>Description</th>
      	  <th>Operations</th>
  		</tr>
  	  </thead>
  	  <tbody>
  		<% @issue_types.each do |issue| %>
  	  	<tr>
  		  <td><%= issue.name %></td>
  		  <td></td>
  		  <td>
  		  <%= link_to 'Edit', edit_project_issue_type_path(@project, issue), :class => 'btn btn-mini', :remote => true, :data => { :toggle => 'modal', :target => '#edit_issue_type_modal' } %>
          <%= link_to 'Destroy', project_issue_type_path(@project, issue), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
          </td>
  	  	</tr>
    	<% end %>
  	  </tbody>
	</table>
	<%= link_to 'Add Issue Type', new_project_issue_type_path, :class => 'btn btn-primary', :remote => true, :data => { :toggle => 'modal', :target => '#new_issue_type_modal' } %>

	<div id="new_issue_type_modal" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"> </div>
  <div id="edit_issue_type_modal" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"> </div>
  </div>
</div>

app/views/issue_types/new.js.erb
$("#new_issue_type_modal").html("<%= escape_javascript(render 'new_issue_type_modal') %>");