config/routes.rb
SampleApp::Application.routes.draw do

  get "projects/new"

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  resources :projects do
    resources :issue_types
  end

  

  root :to => 'sessions#new'

  match '/signup', :to => 'users#new'
  match '/signout', :to => 'sessions#destroy', via: :delete
    

  match '/help', :to => 'static_pages#help'
  match '/about', :to => 'static_pages#about'
  match '/contact', :to => 'static_pages#contact'
 

  match 'substantive_content', :to => 'projects#substantive_content'
  match 'projects/:id/donot_know', :to => 'projects#donot_know', as: :projects_donot_know

  match 'projects/:id/issues', :to => 'projects#issues', as: :projects_issues
  match 'projects/:id/new_issue', :to=>'projects#new_issue', as: :new_project_issue
  
  

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :project_lead

  has_many :issue_types, dependent: :destroy

  has_many :project_user_associations
  has_many :users, through: :project_user_associations, dependent: :destroy;

  validates :name, presence: true, length: { maximum: 80 }
  validates :project_lead, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :desroy] 
  before_filter :admin_user, only: [:index, :edit, :update, :desroy]

  include ProjectsHelper
  
  def index
    if current_user.admin?
  	   @projects = Project.all
       @project = Project.new
    else 
    end
  end

  def new
  	@project = Project.new
    #respond_to do |format|               
     # format.js
    #end
  end

  def create
    #@project = Project.new(params[:project])

    @project = current_user.projects.create(params[:project])
    # binding.pry
    respond_to do |format|
      if @project.errors.count <= 0
        populate_issue_types @project
        format.html { redirect_to @project, notice: 'Project Created!' }
        format.json { render json: @project, status: :created, location: @project }
      else
        puts 'hell'
        format.html { render 'new' }
        format.json { render json: @project.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def show
  	@project = Project.find(params[:id])
    @issues = @project.issue_types.all
  end

  def edit
    @project = Project.find(params[:id])
    respond_to do |format|               
      format.js
    end
  end
  
  def update
	  @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      # Handle a successful update
      flash[:success] = "Project updated."
      # sign_in @user
      redirect_to :back
    else
      redirect_to :back
    end
  end
  
  def destroy
  	Project.find(params[:id]).destroy
  	flash[:success] = "Project destroyed."
    redirect_to projects_url
  end

  def substantive_content
    respond_to do |format|               
      format.js
    end        
  end 

  def donot_know
    @project = Project.find(params[:id])
    @issues = @project.issue_types.all
    respond_to do |format|               
      format.js
    end  
  end

  def issues
    @project = Project.find(params[:id])
    @issue_types = @project.issue_types.all
    respond_to do |format|               
      format.js
    end  
  end

  def new_issue
    @project = Project.find(params[:id])
    @issue_type = @project.issue_types.build
    respond_to do |format|               
      format.js
    end
  end

  private

    def admin_user
      redirect_to (root_path) unless current_user.admin?
    end
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
  ISSUETYPES = ['Bug', 'Improvement', 'New Feature']
  def projectlead_for(project)
	User.find(project.project_lead).name
  end


  def populate_issue_types(project)
  	ISSUETYPES.each do |issue|
  		@issuetype = project.issue_types.build(name: issue)
  		@issuetype.save
  	end
  end
end

app/views/projects/_edit_project_modal.html.erb
<%= form_for(@project) do |f| %>
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h3>Edit Project</h3>
</div>
<div class="modal-body">
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label 'Project Lead' %>
  <%= collection_select(:project, :project_lead, User.all, :id, :name, :prompt => true) %>  
</div>
<div class="modal-footer">
  <a href="#" class="btn">Close</a>
  <%= f.submit 'Update', class: "btn btn-large btn-primary" %>
</div>
<% end %>

app/views/projects/_hello.html.erb
<table class="table table-striped">
  <thead>
  	<tr>
  	  <th>Issue Type</th>
  	  <th>Description</th>
      <th>Operations</th>
  	</tr>
  </thead>
  <tbody>
  	<% @issue_types.each do |issue| %>
  	  <tr>
  		<td><%= issue.name %></td>
  		<td></td>
  		<td>
  		  <%= link_to 'Edit', '#', :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', '#', :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
  	  </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Add Issue Type', '#', :class => 'btn btn-primary' %>

<%= link_to 'My modal', new_project_issue_path, :class => 'btn', :remote => true, :data => { :toggle => 'modal', :target => '#new_issue_modal' } %>

<div id="new_issue_modal" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>


app/views/projects/_left_menu.html.erb
<ul class="nav nav-list nav-stacked">
  <li><%= link_to 'Summary', '#' %></li>
  <li class="divider"></li>
  <li><%= link_to 'Issue Types', project_issue_types_path(@project) %>
  <li><%= link_to 'Workflow', '#' %></li>
  <li class="divider"></li>
  <li><%= link_to 'Test', substantive_content_path, :remote => true %></li>
  <li><%= link_to 'I donot know', projects_donot_know_path, :remote => true %></li>
  <li><%= link_to 'Issue Types', projects_issues_path, :remote => true %></li>
  <li><a href="#">Contact</a></li>
</ul>

app/views/projects/_new_issue.html.erb

  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Modal header</h3>
  </div>
  <div class="modal-body">
   <%= form_for @issue_type do |f| %>
      <%= hidden_field_tag "project_id", @project.id %>
      Name
      <%= f.text_field :name %>
      <!--more form fields-->
      <%= f.submit "Add Driver", class: "btn btn-large btn-primary" %>
    <% end %>  
  </div>
  <div class="modal-footer">
    <a href="#" class="btn">Close</a>
    <a href="#" class="btn btn-primary">Save changes</a>
  </div>

app/views/projects/_project_info.html.erb
<div class="row">
  <div class="span8">
  	<div>
      <%= @project.name %>
	</div>
	<div>
      Lead: <%= projectlead_for @project %>
	</div>
  </div>
  <div class="pull-right">
  	<%= link_to 'Edit', edit_project_path(@project), :class => 'btn' %>
    <%= link_to 'Destroy', project_path(@project), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
  </div>
</div>

app/views/projects/edit.html.erb
<% provide(:title, 'Projects') %>
<h1>Edit Project</h1>
<div class="row">
  <div class="span6 offset3">
  	<%= form_for(@project) do |f| %>
  	  <%= render 'shared/error_messages', object: f.object %>
  	  <%= f.label :name %>
  	  <%= f.text_field :name %>
  	  <%= f.label 'Project Lead' %>
  	  <%= collection_select(:project, :user_id, User.all, :id, :name, :prompt => true) %>
  	  <%= f.submit 'Update', class: "btn btn-large btn-primary" %>
  	<% end %>
  </div>
</div>

app/views/projects/edit.js.erb
$("#edit_project_modal").html("<%= escape_javascript(render 'edit_project_modal') %>");

app/views/projects/index.html.erb
<% provide(:title, 'All projects') %>
<h1>All projects</h1>
<table class="table table-striped">
  <thead>
  	<tr>
  	  <th>Project</th>
  	  <th>Project Lead</th>
  	  <th>Created at</th>
      <th>Operations</th>
  	</tr>
  </thead>
  <tbody>
  	<% @projects.each do |project| %>
  	  <tr>
  		<td><%= link_to project.name, project %></td>
  		<td><%= link_to projectlead_for(project), :controller=>"users", :action=>"show", :id => project.project_lead %></td>
  		<td><%= project.created_at %></td>
  		<td>
  		  <%= link_to 'Edit', edit_project_path(project), :class => 'btn btn-mini', :remote => true, :data => { :toggle => 'modal', :target => '#edit_project_modal' } %>
          <%= link_to 'Destroy', project_path(project), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
  	  </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Add Project', new_project_path, :class => 'btn btn-primary', :remote => true, :data => { :toggle => 'modal', :target => '#new_project_modal' } %>

<%= link_to 'New Project', '#new-project-modal', 'data-toggle' => "modal" %>

<div id="new_project_modal" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"> </div>
<div id="edit_project_modal" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"> </div>


<div id='new-project-modal' class='modal hide fade'>
  <div class = "modal-header">
    <div id="error_explanation" style="display:none;">
    </div>
  </div>
<div class = "modal-body">
  <%= form_for(@project, remote: true, html: {"data-type" => :json}) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label 'Project Lead' %>
    <%= collection_select(:project, :project_lead, User.all, :id, :name, :prompt => true) %>
</div>
<div class = "modal-footer">
  <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
</div>
<% end %>
</div>
<script type="text/javascript">
$('#new-project-modal').on('show', function (e) {
    $('#error_explanation').hide()
})
</script>




app/views/projects/issues.js.erb
$('#content').html("<%= escape_javascript(render(:partial => 'hello')) %>");

app/views/projects/new.html.erb
<% provide(:title, 'Projects') %>
<h1>Add a new project</h1>
<div class="row">
  <div class="span6 offset3">
  	<%= form_for(@project) do |f| %>
  	  <%= render 'shared/error_messages', object: f.object %>
  	  <%= f.label :name %>
  	  <%= f.text_field :name %>
  	  <%= f.label 'Project Lead' %>
  	  <%= collection_select(:project, :project_lead, User.all, :id, :name, :prompt => true) %>
  	  <%= f.submit 'Submit', class: "btn btn-large btn-primary" %>
  	<% end %>
  </div>
</div>

app/views/projects/new.js.erb
$("#new_project_modal").html("<%= escape_javascript(render 'new_project_modal') %>");

app/views/projects/new_issue.js.erb
$("#new_issue_modal").html("<%= escape_javascript(render 'new_issue') %>");

app/views/projects/show.html.erb
<%= provide(:title, @project.name) %>
<%= render 'project_info' %>
<div class="row">
  <div class="span2">
    <%= render 'left_menu' %>
  </div>
  <div id="content" class="span8">
  </div>
</div>

app/views/projects/substantive_content.js.erb
$('#content').html("<%= render :partial => 'hello' %>");