config/routes.rb
SampleApp::Application.routes.draw do

  get "projects/new"

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  resources :projects do
    resources :issue_types
  end

  

  root :to => 'sessions#new'

  match '/signup', :to => 'users#new'
  match '/signout', :to => 'sessions#destroy', via: :delete
    

  match '/help', :to => 'static_pages#help'
  match '/about', :to => 'static_pages#about'
  match '/contact', :to => 'static_pages#contact'
 

  match 'substantive_content', :to => 'projects#substantive_content'
  match 'projects/:id/donot_know', :to => 'projects#donot_know', as: :projects_donot_know

  match 'projects/:id/issues', :to => 'projects#issues', as: :projects_issues
  match 'projects/:id/new_issue', :to=>'projects#new_issue', as: :new_project_issue
  
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    8848m &copy; 2013
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "doppio", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <% if current_user.admin? %>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Administration <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Projects", projects_path %></li>
                  <li><%= link_to "User Management", '#' %></li>
                  <li><%= link_to "Issues", '#' %></li>
                </ul>
              </li>
            <% end %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
              </ul>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![Endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %> </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>